[package]
name = "rusty_beagle"
version = "0.1.0"
edition = "2021"

[dependencies]
gpiod = "0.3.0"
log = "0.4.22"
ron = "0.8.1"
serde = { version = "1.0.204", features = ["derive"] }
spidev = "0.6.0"
syslog = "^6.0"

