#!/usr/bin/bash

echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Packet sent."
echo "Received"
echo "Received"
echo "Received"
echo "Received"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
echo "CRC Error"
