[lora_config]
mode = "TX"
reset_gpio = "GPIO_67"
dio0_gpio = "GPIO_68"

[lora_config.spi_config]
spidev_path = "/dev/spidev1.0"
bits_per_word = 8
max_speed_hz = 500000
lsb_first = false
spi_mode = "SPI_MODE_0"

[lora_config.radio_config]
frequency = 433000000
bandwidth = "bandwidth_31_25kHz"
coding_rate = "coding_4_8"
spreading_factor = "spreading_factor_4096"
tx_power = 17
